# -*- coding: utf-8 -*-
"""exercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFw1t1OEvA8AZz8flshEgxTuyKkVDdgR
"""

print("Olá! É um prazer tê-lo aqui.")
nome = input("Para começarmos, por favor, digite seu nome: ")

while True:
    resposta = input("Deseja calcular? \nDigite 'S' para sim e 'N' para não: ").lower()
    if resposta in ('s', 'sim'):
        print("Vamos continuar.")
        break
    elif resposta in ('n', 'não'):
        print("Até outra hora.")
        exit()
    else:
        print("Caracter inválido. Encerrando o programa.")
        exit()

num1 = 0
num2 = 0
result = 0
op = ' '

while True:
    num1 = float(input("\nDigite o primeiro valor: "))
    print("Escolha:\n'+' para soma.\n'-' para subtração\n'*' para multiplicação\n'/' para dividir\n")
    op = input("Digite a operação em que deseja calcular: ")
    num2 = float(input("\nDigite o segundo valor: "))

    if op == '+':
        result = num1 + num2
    elif op == '-':
        result = num1 - num2
    elif op == '*':
        result = num1 * num2
    elif op == '/':
        result = num1 / num2
    else:
        print("Operação não reconhecida.")

    print("Olá,", nome,"aqui esta seu calculo: {} {} {} = {}".format(num1, op, num2, result))

    continuar = input("Deseja realizar outra operação? (S/N): ").lower()
    if continuar in ('s', 'sim'):
            continue
    elif continuar in ('n', 'não'):
            print("Até a próxima!")
            break
    else:
            print("Caracter inválido. Reiniciando o programa.")
            exit()